name: Generate Dependency Check Artifacts

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  upload-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Vulnerability Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-reports
          path: data/*.json
          retention-days: 7